### ISSUE TITLE
Build missing on site.

### ISSUE THREAD

**Issue by TheMorc** [gulrak/relive-client#4]
Hi, this is not so much a reLiveG problem as it is a problem with the link to it. The build for macOS on https://relive.gulrak.net/reliveg/ shows a 404 not found.

**Comment by gulrak** [comment]
Yeah, stupid me used the wrong address. Fixed the website links, and [this is the link to the v0.7.53 macOS binary](https://relive.gulrak.net/reliveg/macos/reliveg-v0.7.53-macos.zip)
